routes/web.php
<?php

Auth::routes();

Route::get('/verifyUser/{id}', 'Admin\UsersController@verify');

//Route::get('send', 'DeliveryReportController@send');
Route::post('delivery_report', 'DeliveryReportController@saveDeliveryReport');

Route::group(['namespace' => 'Auth', 'as' => 'auth::'], function()
{
    Route::get('accept/{token}', 'LoginController@acceptInvite')->name('teams.accept_invite');
    Route::get('customer_services/verify/{verification_code}', 'VerifyCustomerServiceController@verifyService')->name('services.verify_mail');
    Route::get('cron', 'CronController@run')->name('cron.run');
});

//Route::get('/pending_users', 'HomeController@nonMigratedUsers');
Route::get('/migrate_users', 'HomeController@migrateUsers');

Route::get('/home', function(){
    return redirect('/', 301);
});

Route::group(['namespace' => 'Front', 'prefix' => 'management','as' => 'front::','middleware' => ['auth', 'role:customer'] ], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::get('active_services', 'ServiceController@indexUserServices')->name('services.userServiceIndex');
    Route::get('service_calls', 'ServiceController@indexServiceCalls')->name('services.ServiceCallIndex');
    Route::get('payment_history', 'ServiceController@paymentHistory')->name('services.PaymentHistory');
    Route::get('active_services/{id}', 'ServiceController@viewUserServices')->name('services.userServiceView');
    Route::match(['GET', 'POST'], 'profit_and_loss', 'ServiceController@profitAndLoss')->name('services.profitAndLoss');
    Route::match(['GET', 'POST'], 'profit_and_loss_stock', 'ServiceController@profitAndLossStock')->name('services.profitAndLossStock');

    Route::get('profile', 'UserController@viewProfile')->name('users.viewProfile');
    Route::match(['GET', 'POST'], 'profile/edit', 'UserController@edit')->name('users.edit');
    Route::match(['GET', 'POST'], 'profile/change-password', 'UserController@changePassword')->name('users.changePassword');

    Route::get('messages', 'UserController@messages')->name('users.messages');

});

Route::group(['namespace' => 'Admin', 'as' => 'admin::','middleware' => ['auth', 'restrict_ip', 'role:super-admin|manager|normal-user|pre-sales|retail-sales|hni-sales|manager-1|customer'] ], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard');

});

//please define allowed roles to access this route here like -> 'role:super-admin|manager' in middleware
Route::group(['namespace' => 'Admin', 'as' => 'admin::','middleware' => ['auth', 'restrict_ip', 'role:super-admin|manager|normal-user|pre-sales|retail-sales|hni-sales|manager-1'] ], function () {

    //Route::get('/', 'DashboardController@index')->name('dashboard');

     /**
     * CLIENTS
     */
    Route::get('clients/index', 'ClientsController@index')->name('clients.index');
    Route::get('clients/data', 'ClientsController@anyData')->name('clients.data');

    Route::get('clients/get_relationship', 'ClientsController@getRelationshipManager');
    Route::get('clients/get_compliance', 'ClientsController@getComplianceManager');

    Route::post('clients/store_client_new', 'ClientsController@storeClientNew')->name('store_client_new');

    Route::get('customers', 'ClientsController@indexCustomers')->name('clients.customers');
    Route::post('customerData', 'ClientsController@customerData')->name('clients.customerData');
    Route::match(['GET', 'POST'],'customers/{id}', 'ClientsController@showCustomer')->name('clients.customerShow');
    Route::get('customers/{id}/pnl_service', 'ClientsController@profitAndLossStock')->name('clients.customerPnlService');
    Route::get('customers/destroy/{id}', 'ClientsController@destroyCustomer')->name('customers.destroy');

    Route::get('clients/createDirect', 'ClientsController@createDirect')->name('clients.createDirect');
    Route::post('clients/create/cvrapi', 'ClientsController@cvrapiStart');
    //Route::post('clients/upload/{id}', 'DocumentsController@upload');
    Route::resource('clients', 'ClientsController');
    Route::post('clients/destroy/{id}', 'ClientsController@destroy')->name('clients.destroy');
    Route::post('clients/storeClientUser', 'ClientsController@storeClientUser')->name('clients.store_client_user');
    Route::post('clients/updateClientUserInfo', 'ClientsController@updateClientUserInfo')->name('clients.update_client_user_info');
    Route::get('clients/{id}/addService', 'ClientsController@addService')->name('clients.addService');
    Route::post('clients/addClientService', 'ClientsController@addClientService')->name('clients.addClientService');
    Route::post('clients/sendClientSms', 'ClientsController@sendClientSms')->name('clients.send_sms');
    Route::post('clients/sendClientEmail', 'ClientsController@sendClientEmail')->name('clients.send_email');
    Route::match(['GET', 'POST'],'clients/addToWatch/{id}', 'ClientsController@addToWatchList')->name('clients.add_to_watch');

    Route::get('client/download_pnl/{id}', 'ClientsController@downloadPnl')->name('clients.download_pnl');
    Route::post('client/share_pnl/{id}', 'ClientsController@sharePnl')->name('clients.share_pnl');
    Route::get('client/watched', 'ClientsController@getWatchlistUser')->name("clients.watched_by_me");

    Route::get('client/get_pending_service_activation', 'ClientsController@getPendingServiceActivation')->name("clients.get_pending_service_activation");
    Route::post('client/update_pending_service_activation', 'ClientsController@updatePendingServiceActivation')->name("clients.update_pending_service_activation");
    /**
    * LEADS
    */
    Route::get('leads/data/{type}', 'LeadsController@anyData')->name('leads.data');
    Route::resource('leads', 'LeadsController');
    Route::patch('leads/updateassign/{id}', 'LeadsController@updateAssign');
    Route::post('leads/notes/{id}', 'NotesController@store');
    Route::patch('leads/updatestatus/{id}', 'LeadsController@updateStatus')->name('leads.updatestatus');
    Route::patch('leads/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    Route::patch('leads/updatebasicinfo/{id}', 'LeadsController@updateBasicInfo')->name('leads.basicinfo');

    Route::patch('leads/completeLead/{id}', 'LeadsController@completeLead')->name('leads.completeLead');

    Route::get('leads/{id}', 'LeadsController@show')->name('leads.show');
    Route::post('leads/destroy/{id}', 'LeadsController@destroy')->name('leads.destroy');
    Route::post('leads/{id}/edit/', 'LeadsController@edit')->name('leads.edit');

    /**
    * DEPARTMENTS
    */
    Route::resource('departments', 'DepartmentsController');
    Route::post('departments/destroy/{id}', 'DepartmentsController@destroy')->name('departments.destroy');

    Route::resource('designations', 'DesignationsController');


    Route::match(['GET', 'POST'], 'users/{users}/changepassword', 'UsersController@changePassword')->name('users.changepassword');
    Route::match(['GET'], 'users/{users}/passwordsettings', 'UsersController@passwordSettings')->name('users.passwordsettings');
    Route::match(['GET'], 'users/{users}/logs', 'UsersController@logs')->name('users.logs');
    Route::match(['GET'], 'users/activities', 'UsersController@activities')->name('users.activities');
    Route::match(['GET', 'POST'], 'users/showpermission', 'UsersController@showPermission')->name('users.showpermission');

    Route::match(['GET'], 'users/{users}/{roles}/edit', 'UsersController@edit')->name('users.edit');
    Route::match(['GET', 'POST'], 'users/note', 'UsersController@note')->name('users.note');
    Route::match(['GET', 'POST'], 'users/copyimage', 'UsersController@copyImage')->name('users.copyimage');
    Route::match(['GET', 'POST'], 'users/designation', 'UsersController@designationList')->name('users.designation');
    Route::match(['GET', 'POST'], 'users/selectdesignation', 'UsersController@selectDesignation')->name('users.selectdesignation');
    Route::match(['GET', 'POST'], 'users/searchbar', 'UsersController@searchBar')->name('users.searchbar');
    Route::match(['GET', 'POST'], 'users/add', 'UsersController@addDepartment')->name('users.add');
    Route::match(['GET', 'POST'], 'users/check', 'UsersController@checkUsername')->name('users.check');
    Route::match(['GET', 'POST'], 'users/getcity', 'UsersController@getCity')->name('users.getcity');
    Route::match(['GET', 'POST'], 'users/getzipcode', 'UsersController@getZipcode')->name('users.getzipcode');
    Route::match(['GET', 'POST'], 'users/savedesignation', 'UsersController@saveDesignation')->name('users.savedesignation');
    Route::post('users/alluser', 'UsersController@allUser')->name('users.alluser');

    Route::resource('users', 'UsersController');

    Route::match(['GET', 'POST'], 'roles/{role}/permissions', 'RolesController@addPermissions')->name('roles.permissions');
    Route::resource('roles', 'RolesController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('templates', 'TemplatesController');
    Route::resource('tokens', 'TokensController');
    //Route::resource('companies', 'CompanyMastersController');
    Route::get('company/import/{date?}', 'CompanyController@importBhav');
    Route::get('company/get_upload_excel_page', 'CompanyController@addExcel');
    Route::post('company/upload_fundasheet', 'CompanyController@uploadFundasheet');
    Route::resource('company', 'CompanyController');

    Route::post('settings/manage/ip/selectteam', 'SettingsController@getTeam')->name('manage_ip.selectteam');
    Route::post('settings/manage/ip/selectuser', 'SettingsController@getUser')->name('manage_ip.selectuser');
    Route::get('settings/manage/ip/{type}', 'SettingsController@manageIp')->name('manage_ip.show');
    Route::post('settings/manage/ip/{type}', 'SettingsController@updateIp')->name('manage_ip.update');

    Route::get('settings/manage/watchlist/stock', 'SettingsController@indexWatchlistStock')->name('stock_watchlist.index');

app/Models/Client.php
<?php
namespace App\Models;

//use App\Libraries\Traits\RecordsActivity;
use App\Libraries\Traits\RothmansUserTrait;
use Illuminate\Database\Eloquent\Model;
use Carbon;

class Client extends Model
{

     use  RothmansUserTrait;//, RecordsActivity;
    protected $fillable = [
            'name',
            'company_name',
            'fk_service_id',
            'email',
            'address',
            'zipcode',
            'city',
            'primary_number',
            'secondary_number',
            'company_type'];

    public function userAssignee()
    {
        return $this->belongsTo(User::class, 'fk_user_id', 'id');
    }

    public function alltasks()
    {
        return $this->hasMany(Tasks::class, 'fk_client_id', 'id')
        ->orderBy('status', 'asc')
        ->orderBy('created_at', 'desc');
    }

    public function allleads()
    {
        return $this->hasMany(Leads::class, 'fk_client_id', 'id')
        ->orderBy('status', 'asc')
        ->orderBy('created_at', 'desc');
    }

    public function service()
    {
        return $this->hasOne(Service::class, 'fk_service_id', 'id');
    }

    public function tasks()
    {
        return $this->hasMany(Tasks::class, 'fk_client_id', 'id');
    }
    public function leads()
    {
        return $this->hasMany(Tasks::class, 'fk_client_id', 'id');
    }
    public function documents()
    {
        return $this->hasMany(Document::class, 'fk_client_id', 'id');
    }
    public function invoices()
    {
        return $this->belongsToMany(Invoice::class);
    }
}

resources/views/admin/clients/tabs/activeservicestab.blade.php
<div id="services" class="tab-pane fade in">
  <div class="boxspace">
    <div class="panel panel-flat table-responsive small">
        <table class="table table-hover" id="customers-table">
        <tbody>

        <tr>
            <th>Service Count</th>
            <td>{{ $pnl_all['service_count']}}</td>
        </tr>

        <tr>
            <th>Total Capital</th>
            <td>{{ $pnl_all['total_capital'] }}</td>
        </tr>

        <tr>
            <th>Total calls</th>
            <td>{{ $pnl_all['total_calls']}}</td>
        </tr>
        <tr>
            <th>Positive Calls</th>
            <td>{{ $pnl_all['positive_call'] }}</td>
        </tr>

        <tr>
            <th>Total P&L</th>
            <td>{{ $pnl_all['total_profit'] }}</td>
        </tr>
        <tr>
            <th>Today's Pnl</th>
            <td>{{ $pnl_all['today_pnl'] }}</td>
        </tr>

        </tbody>
        </table>
    </div>
    <div class="clearfix"></div>
    <a href="{!! route('admin::clients.addService', $user->id) !!}" class="btn btn-primary pull-right">Add New Service</a>
    <div class="clearfix"></div>
    <br>
    <div class="table-responsiv">
      <table class="table table-striped table-hover table-bordered text-center">
        <thead>
          <tr class="bg-blue">
            <th rowspan="2" class="text-center" width="50">#</th>
            <th rowspan="2" class="text-center">Service</th>
            <th rowspan="2" class="text-center">Plan</th>
            <th colspan="4" class="text-center">Amount</th>
            <th colspan="2" class="text-center">Date</th>
            <th rowspan="2" class="text-center" width="85">Status</th>
            <th rowspan="2" class="text-center" width="125">Actions</th>
          </tr>
          <tr class="bg-blue">
            <th class="text-center" width="100">Service Capital</th>
            <th class="text-center" width="100">Payable</th>
            <th class="text-center" width="100">Paid</th>
            <th class="text-center" width="100">Uncleared</th>
            <th class="text-center" width="115">Activation</th>
            <th class="text-center" width="115">Expiry</th>
            <!--<th class="text-center" width="125">Created</th>-->
          </tr>
        </thead>
        <tbody>
        <?php $total_capital = $total_payable = $total_paid = $total_uncleared = 0; ?>
        @forelse($user_services as $key => $user_service)
          <tr>
            <td>{{$key+1}}</td>
            <td>{{$user_service->service->name}}</td>
            <td>{{$user_service->plan->name}}</td>
            <?php
            foreach ($user_service->transections as $transaction) {
              if($user_service->latest_transaction_history_id == $transaction->transaction_history_id){
                $amount_payable = $transaction->payable_amount;
              } else {
                $amount_payable = 0;
              }
            }
            if(isset($user_service->transections)) {
              $all = $user_service->transections->toArray();
              if(count($all) > 0){
                $amount_paid = array_sum(
                  array_map(
                    function($item) use ($user_service)  {
                      if($item['cleared'] == 'Yes' && $user_service->latest_transaction_history_id == $item['transaction_history_id']) { 
                        return $item['amount']; 
                      } else { 
                        return 0; 
                      } 
                    }, $all
                  )
                );
              }
            }

            $balance = round($amount_payable, 0, PHP_ROUND_HALF_UP) - round($amount_paid, 0, PHP_ROUND_HALF_UP);
            $total_capital = $total_capital+$user_service->service_capital;
            $total_payable = $total_payable+$amount_payable;
            $total_paid = $total_paid+$amount_paid;
            $total_uncleared = $total_uncleared+$balance;
            ?>
            <td>{{($user_service->service_capital > 0)?'Rs.'.$user_service->service_capital:'N/A'}}</td>
            <td>Rs. {{$amount_payable}}</td>
            <td>Rs. {{$amount_paid}}</td>
            <td>Rs. {{$balance}}</td>
            <td>{{(new Carbon($user_service->activation_date))->format('d-m-Y')}}</td>
            <td>{{(!empty($user_service->expire_date))?((new Carbon($user_service->expire_date))->format('d-m-Y')):'N/A'}}</td>
            <!--
            <td>{{(new Carbon($user_service->created_at))->format('d-m-Y h:i A')}}</td>
            -->
            <td>
              @if($user_service->service_status == 'Active')
                <label class="bg-success text-highlight">{{$user_service->service_status}}</label>
              @else
                <label class="bg-warning text-highlight">{{$user_service->service_status}}</label>
              @endif
            </td>
            <td>
              <?php
                $activation_date = new Carbon($user_service->activation_date);
                if(!empty($user_service->plan->duration)){
                  $expiry_date = $activation_date->subDay()->addDays($user_service->plan->duration)->format('d-m-Y');
                } else {
                  $expiry_date = $activation_date->subDay()->addDays($user_service->plan->duration)->format('d-m-Y');
                }
              ?>
              
                
              <ul class="icons-list">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <i class="icon-gear"></i>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <!--
                        @if($user_service->consent_status == 'No')
                          <li>
                              <a href="{{route('admin::user_services.resendVerification', $user_service->id)}}" class="resend_activation"><i class="icon-alarm-check"></i> Resend Activation</a>
                          </li>
                        @endif
                        <li>
                            <a 
                              href="javascript:"
                              data-s_name ="{{$user_service->service->name}}"  
                              data-s_plan ="{{$user_service->plan->name}}"  
                              data-id="{{$user_service->id}}" 
                              data-transcript="{{$user_service->transcript_status}}" 
                              data-kyc="{{$user_service->kyc_status}}" 
                              data-consent="{{$user_service->consent_status}}" 
                              data-activation-date="{{(new Carbon($user_service->activation_date))->format('d-m-Y')}}" data-expiry-date="{{$expiry_date}}" 
                              data-balance-warning="{{($balance > 0)?'yes':'no'}}"
                              data-consent-ip="{{$user_service->consent_ip}}"
                              class="service_verify"
                            >
                                <i class="icon-file-check2"></i> Verify Service
                            </a>
                        </li>
                      -->
                        <li>
                            <a href="{{route('admin::user_services.showUserService', $user_service->id)}}"><i class="icon-eye2"></i> View</a>
                        </li>
                        <li>
                          <a href="{{route('admin::active_service.edit', $user_service->id)}}"><i class="icon-pencil7"></i> Edit</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                          <a href="{{route('admin::active_service.renew', $user_service->id)}}"><i class="icon-reload-alt"></i> Renew</a>
                        </li>
                        <li>
                            <a href="{{route('admin::services.tempExtnService')}}" class="modal-action" data-toggle="modal" data-id="{{$user_service->id}}" data-action="temp_extn" data-target="#action_modal"><i class="icon-move-horizontal"></i> Temp Extn</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{route('admin::services.terminateService')}}" class="modal-action" data-toggle="modal" data-id="{{$user_service->id}}" data-action="terminate" data-target="#action_modal"><i class="icon-x"></i> Terminate</a>
                        </li>
                        <li>
                            <a href="{{route('admin::services.destroyActiveServices', $user_service->id)}}" class="text-danger-700 btn-delete"><i class="icon-trash"></i> Delete</a>
                        </li>
                    </ul>
                </li>
            </ul>
            </td>
          </tr>
        @empty
          <tr>
            <td colspan="11">
              <div class="alert bg-warning alert-rounded">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                <span class="text-semibold">No Data!</span> No Services Assigned.
              </div>
            </td>
          </tr>
        @endforelse
        @if(!empty($user_services))
          <tr class="bg-info">
            <td colspan="3"> Total Amount</td>
            <td>Rs. {{$total_capital}}</td>
            <td>Rs. {{$total_payable}}</td>
            <td>Rs. {{$total_paid}}</td>
            <td>Rs. {{$total_uncleared}}</td>
            <td colspan="4"></td>
          </tr>
        @endif
        </tbody>
      </table>
    </div>
  </div>
</div>
@include('admin.partials.action_modal')
<div id="verify_modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
          <form class="verify_modal_form" id="verify_form" action="{{route('admin::verifyService')}}" enctype="multipart/form-data">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h5 class="modal-title">Verify Customer</h5>
            </div>
            <div class="modal-body">
              <input type="hidden" class="user_id" name="user_id" value="">
              <div class="col-md-6">
                <label class="checkbox-inline">
                  <input type="checkbox" name="transcript_status" value="yes" class="transcript_status checkbox">
                  <span class="text-bold text-danger">Transcript of Onboarding call</span>
                </label>
              </div>
              <div class="col-md-6 transcript_file" style="display:none;">
                <input type="file" name="transcript_file" class="file-styled">
              </div>
              <div class="clearfix"></div>
              <br>
              <div class="col-md-6">
                <label class="checkbox-inline">
                  <input type="checkbox" name="kyc_status" value="yes" class="kyc_status checkbox">
                  <span class="text-bold text-danger">KYC Form</span>
                </label>
              </div>
              <div class="col-md-6 kyc_file" style="display:none;">
                <input type="file" name="kyc_file" class="file-styled">
              </div>
              <div class="clearfix"></div>
              <br>
              <div class="col-md-6">
                <label class="checkbox-inline">
                  <input type="checkbox" name="consent_status" value="yes" class="consent_status checkbox">
                  <span class="text-bold text-danger">Consent</span>
                </label>
              </div>
              <div class="col-md-6">
                <p><strong>Consent IP : </strong><span class="consent_ip"></span></p>
              </div>
              <div class="clearfix"></div>
              <br>
              <div class="col-md-12" style="margin:10px 0px;">
                 <div id="verify_success" class="alert alert-success" style="display:none;"></div>
                 <div id="verify_failed" class="alert alert-danger" style="display:none;"></div>
              </div>
            </div>
            <div class="modal-footer">
              <span class="verify_service_form_spinner" style="display:none;">
                <i class="icon-spinner2 spinner"></i>
              </span>
              <button type="submit" class="btn btn-primary save_verification">Save</button>
              <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
            </div>
          </form>
            <div id="modal_content_append"></div>
        </div>
    </div>
</div>

@push('scripts')
<script type="text/javascript">

    $('.daterange-delivery_range').daterangepicker({
        applyClass: 'bg-info',
        cancelClass: 'btn-default',
        locale: {
            format: 'DD/MM/YYYY'
        }
    });
    // Enable Select2 select for the length option
    $('select').select2({
        minimumResultsForSearch: Infinity
    });

    $('.pnl_service_model').on('click', function(e){
        e.preventDefault();
        $('#PnLServiceModel').modal('show').find('.modal-title').text($(this).text())
        $('#PnLServiceModel').modal('show').find('.modal-body').html('<p>Loading...</p>').load($(this).attr('href'));
    }).on('show.bs.modal', function () {
        $(this).find('.modal-body').css({
            width:'auto', //probably not needed
            height:'auto', //probably not needed
            'max-height':'100%'
        });
    });
</script>

@endpush

resources/views/admin/clients/tabs/documenttab.blade.php
<div id="docuemnt" class="tab-pane fade">
  <table class="table">
    <h4>All Documents</h4>
    <div class="col-xs-10">
      <div class="form-group">
        <form method="POST" action="{{ url('/clients/upload', $client->id)}}" class="dropzone" id="dropzone" files="true" data-dz-removea
          enctype="multipart/form-data"
          >
          <meta name="csrf-token" content="{{ csrf_token() }}">
        </form>
        <p><b>max 5MB pr. file</b></p>
      </div>
    </div>
    <thead>
      <thead>
        <tr>
          <th>File</th>
          <th>Size</th>
          <th>Created at</th>
          
        </tr>
      </thead>
      <tbody>
        @foreach($client->documents as $document)
        <tr>
          <td><a href="../files/{{$companyname}}/{{$document->path}}"  target="_blank">{{$document->file_display}}</a></td>
          <td>{{$document->size}} <span class="moveright"> MB</span></td>
          <td>{{$document->created_at}}</td>
        </tr>
        @endforeach
      </tbody>
    </table>
    
  </div>

resources/views/admin/clients/tabs/invoicetab.blade.php
<div id="invoice" class="tab-pane fade">
  <div class="boxspace">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Hours</th>
          <th>Total amount</th>
          <th>Invoice sent</th>
          <th>Payment received</th>
        </tr>
      </thead>
      <tbody>
        <?php $total = 0; ?>
        @foreach($invoices as $invoice)
        <tr>
          <td>
            <a href="{{route('invoices.show', $invoice->id)}}">
            {{$invoice->id}}
            </a>
          </td>
          <td>
            <?php $total = 0; ?>
            @foreach($invoice->tasktime as $tasktime)
            <?php $total += $tasktime->time; ?>
            
            @endforeach
            {{$total}}
          </td>
          <td>
            <?php $totalAmount = 0; ?>
            @foreach($invoice->tasktime as $payment)
            <?php $totalAmount += $payment->value; ?>
            @endforeach
            {{$totalAmount}},-
          </td>
          <td>
            @if($invoice->sent == 0)
            <?php $color = "red"; ?>
            @else
            <?php $color = "green"; ?>
            @endif
            <p style=" color:{{$color}}">{{$invoice->sent ? 'yes' : 'no'}}</p>
          </td>
          <td>
            @if($invoice->received == 0)
            <?php $color = "red"; ?>
            @else
            <?php $color = "green"; ?>
            @endif
            <p style=" color:{{$color}}">{{$invoice->received ? 'yes' : 'no'}}</p>
            
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

resources/views/admin/clients/tabs/tasktab.blade.php
<div id="task" class="tab-pane fade in active">
  <div class="boxspace">
    <table class="table table-hover">
      <h4>All Tasks</h4>
      <thead>
        <thead>
          <tr>
            <th>Title</th>
            <th>Assigned user</th>
            <th>Created date</th>
            <th>Deadline</th>
            <th><a href="{{ route('admin::tasks.create', ['client' => $client->id])}}"><button class="btn btn-success">Add new task</button> </a></th>
            
          </tr>
        </thead>
        <tbody>
          <?php  $tr =""; ?>
          @foreach($client->alltasks as $task)
          @if($task->status == 1)
          <?php  $tr = '#adebad'; ?>
          @elseif($task->status == 2)
          <?php $tr = '#ff6666'; ?>
          @endif
          <tr style="background-color:<?php echo $tr ;?>">
            
            <td > <a href="{{ route('tasks.show', $task->id) }}">{{$task->title}} </a></td>
            <td > <div class="popoverOption"
              rel="popover"
              data-placement="left"
              data-html="true"
              data-original-title="<span class='glyphicon glyphicon-user' aria-hidden='true'> </span> {{$task->assignee->name}}">
              <div id="popover_content_wrapper" style="display:none; width:250px;">
                <img src='http://placehold.it/350x150' height='80px' width='80px' style="float:left; margin-bottom:5px;"/>
                <p class="popovertext">
                  <span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span>
                  <a href="mailto:{{$task->assignee->email}}">
                    {{$task->assignee->email}}<br />
                  </a>
                  <span class="glyphicon glyphicon-headphones" aria-hidden="true"> </span>
                  <a href="mailto:{{$task->assignee->work_number}}">
                  {{$task->assignee->work_number}}</p>
                </a>
                
              </div>
              <a href="{{route('users.show', $task->assignee->id)}}"> {{$task->assignee->name}}</a>
              
              </div> <!--Shows users assigned to task -->
            </td>
            <td>{{date('d, M Y, H:i', strTotime($task->created_at))}}  </td>
            <td>{{date('d, M Y', strTotime($task->deadline))}}
            @if($task->status == 1)({{ $task->days_until_deadline }}) @endif</td>
            <td></td>
          </tr>
          
          @endforeach
          
        </tbody>
      </table>
    </div>